"""customers: one person across channels

Creates the customer tables and backfills them from the history every
shop already has — orders first (they carry the phone number, which is
what links a Telegram chat to a web chat), then the leads who have only
ever chatted.

Revision ID: 4f4b53278dfb
Revises: e906d5698031
Create Date: 2026-08-13 09:51:46.163076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f4b53278dfb'
down_revision: Union[str, Sequence[str], None] = 'e906d5698031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('telegram_username', sa.String(length=64), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('orders_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_spent', sa.Float(), server_default='0', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.create_index('ix_customers_tenant_seen', 'customers', ['tenant_id', 'last_seen_at'], unique=False)
    op.create_index('uq_customer_tenant_phone', 'customers', ['tenant_id', 'phone'], unique=True, postgresql_where=sa.text('phone IS NOT NULL'))
    op.create_table('customer_identities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'channel', 'external_id', name='uq_identity_tenant_channel_ext')
    )
    op.create_index(op.f('ix_customer_identities_customer_id'), 'customer_identities', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_identities_tenant_id'), 'customer_identities', ['tenant_id'], unique=False)
    op.add_column('conversations', sa.Column('customer_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_conversations_customer_id'), 'conversations', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'conversations', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    op.add_column('orders', sa.Column('customer_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')

    # ── Backfill ──────────────────────────────────────────────────────────────
    # The tables are useless empty: every shop's history already contains the
    # people this feature is about. Orders come first because they carry the
    # phone number, which is the key that merges channels.
    op.execute(sa.text(r"""
        WITH norm AS (
            SELECT o.tenant_id,
                   CASE
                     WHEN length(regexp_replace(o.customer_phone, '\D', '', 'g')) = 9
                       THEN '+998' || regexp_replace(o.customer_phone, '\D', '', 'g')
                     WHEN length(regexp_replace(o.customer_phone, '\D', '', 'g')) >= 9
                       THEN '+' || regexp_replace(o.customer_phone, '\D', '', 'g')
                     ELSE NULL
                   END AS phone,
                   o.customer_name, o.total_amount, o.status, o.created_at
            FROM orders o
        )
        INSERT INTO customers (id, tenant_id, name, phone, first_seen_at, last_seen_at,
                               orders_count, total_spent)
        SELECT 'cus-' || substr(md5(tenant_id || phone), 1, 12),
               tenant_id,
               (array_agg(customer_name ORDER BY created_at DESC))[1],
               phone,
               min(created_at), max(created_at),
               count(*) FILTER (WHERE status <> 'Bekor qilindi'),
               coalesce(sum(total_amount) FILTER (WHERE status <> 'Bekor qilindi'), 0)
        FROM norm
        WHERE phone IS NOT NULL
        GROUP BY tenant_id, phone
        ON CONFLICT DO NOTHING
    """))

    op.execute(sa.text(r"""
        UPDATE orders o SET customer_id = c.id
        FROM customers c
        WHERE c.tenant_id = o.tenant_id
          AND c.phone = CASE
                WHEN length(regexp_replace(o.customer_phone, '\D', '', 'g')) = 9
                  THEN '+998' || regexp_replace(o.customer_phone, '\D', '', 'g')
                WHEN length(regexp_replace(o.customer_phone, '\D', '', 'g')) >= 9
                  THEN '+' || regexp_replace(o.customer_phone, '\D', '', 'g')
                ELSE NULL END
    """))

    # Conversations whose phone already matches an order-derived customer.
    op.execute(sa.text(r"""
        UPDATE conversations cv SET customer_id = c.id
        FROM customers c
        WHERE c.tenant_id = cv.tenant_id
          AND cv.customer_phone IS NOT NULL
          AND c.phone = CASE
                WHEN length(regexp_replace(cv.customer_phone, '\D', '', 'g')) = 9
                  THEN '+998' || regexp_replace(cv.customer_phone, '\D', '', 'g')
                WHEN length(regexp_replace(cv.customer_phone, '\D', '', 'g')) >= 9
                  THEN '+' || regexp_replace(cv.customer_phone, '\D', '', 'g')
                ELSE NULL END
    """))

    # Everyone else: a lead who has chatted but never ordered. They are exactly
    # the half of the list a shop most wants to call back, so they become
    # customers too — keyed by their channel handle.
    op.execute(sa.text("""
        INSERT INTO customers (id, tenant_id, name, phone, telegram_username,
                               first_seen_at, last_seen_at, orders_count, total_spent)
        SELECT 'cus-' || substr(md5(cv.id), 1, 12), cv.tenant_id,
               cv.customer_name, NULL, cv.customer_username,
               cv.created_at, cv.last_message_at, 0, 0
        FROM conversations cv
        WHERE cv.customer_id IS NULL AND cv.external_id IS NOT NULL
    """))
    op.execute(sa.text("""
        UPDATE conversations cv SET customer_id = 'cus-' || substr(md5(cv.id), 1, 12)
        WHERE cv.customer_id IS NULL AND cv.external_id IS NOT NULL
    """))

    # Finally the channel handles, so the next inbound message finds the person.
    op.execute(sa.text("""
        INSERT INTO customer_identities (tenant_id, customer_id, channel, external_id)
        SELECT DISTINCT ON (cv.tenant_id, cv.channel, cv.external_id)
               cv.tenant_id, cv.customer_id, cv.channel, cv.external_id
        FROM conversations cv
        WHERE cv.customer_id IS NOT NULL AND cv.external_id IS NOT NULL
        ORDER BY cv.tenant_id, cv.channel, cv.external_id, cv.last_message_at DESC
        ON CONFLICT DO NOTHING
    """))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_column('orders', 'customer_id')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_customer_id'), table_name='conversations')
    op.drop_column('conversations', 'customer_id')
    op.drop_index(op.f('ix_customer_identities_tenant_id'), table_name='customer_identities')
    op.drop_index(op.f('ix_customer_identities_customer_id'), table_name='customer_identities')
    op.drop_table('customer_identities')
    op.drop_index('uq_customer_tenant_phone', table_name='customers', postgresql_where=sa.text('phone IS NOT NULL'))
    op.drop_index('ix_customers_tenant_seen', table_name='customers')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
