"""aloqa raqami (operator yo'q holati uchun)

Revision ID: 504005907259
Revises: efd918fb1e48
Create Date: 2026-09-25 15:59:15.551690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '504005907259'
down_revision: Union[str, Sequence[str], None] = 'efd918fb1e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_settings', sa.Column('contact_phone', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_settings', 'contact_phone')
    # ### end Alembic commands ###
