"""knowledge base: delivery, payment, warranty, returns, hours, faq

Revision ID: 69c7a05e88be
Revises: 214e5f10a29f
Create Date: 2026-08-10 17:41:22.300230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69c7a05e88be'
down_revision: Union[str, Sequence[str], None] = '214e5f10a29f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOTE: autogenerate wanted to drop products.search_text and the three
    # search indexes here — it can't see objects created by raw SQL in an
    # earlier migration and treats them as stray. Dropping them silently kills
    # catalog search, so those statements are removed on purpose.
    op.add_column('tenant_settings', sa.Column('delivery_info', sa.Text(), nullable=True))
    op.add_column('tenant_settings', sa.Column('delivery_fee_city', sa.Float(), nullable=True))
    op.add_column('tenant_settings', sa.Column('delivery_fee_regions', sa.Float(), nullable=True))
    op.add_column('tenant_settings', sa.Column('free_delivery_from', sa.Float(), nullable=True))
    op.add_column('tenant_settings', sa.Column('delivery_days_city', sa.String(length=64), nullable=True))
    op.add_column('tenant_settings', sa.Column('delivery_days_regions', sa.String(length=64), nullable=True))
    op.add_column('tenant_settings', sa.Column('payment_info', sa.Text(), nullable=True))
    op.add_column('tenant_settings', sa.Column('warranty_info', sa.Text(), nullable=True))
    op.add_column('tenant_settings', sa.Column('return_policy', sa.Text(), nullable=True))
    op.add_column('tenant_settings', sa.Column('working_hours', sa.String(length=255), nullable=True))
    op.add_column('tenant_settings', sa.Column('faq', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_settings', 'faq')
    op.drop_column('tenant_settings', 'working_hours')
    op.drop_column('tenant_settings', 'return_policy')
    op.drop_column('tenant_settings', 'warranty_info')
    op.drop_column('tenant_settings', 'payment_info')
    op.drop_column('tenant_settings', 'delivery_days_regions')
    op.drop_column('tenant_settings', 'delivery_days_city')
    op.drop_column('tenant_settings', 'free_delivery_from')
    op.drop_column('tenant_settings', 'delivery_fee_regions')
    op.drop_column('tenant_settings', 'delivery_fee_city')
    op.drop_column('tenant_settings', 'delivery_info')
    # ### end Alembic commands ###
