"""knowledge base: delivery, payment, warranty, returns, hours, faq

Revision ID: 69c7a05e88be
Revises: 214e5f10a29f
Create Date: 2026-08-10 17:41:22.300230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69c7a05e88be'
down_revision: Union[str, Sequence[str], None] = '214e5f10a29f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_name_trgm'), table_name='products', postgresql_ops={'sotuvchi_norm(name::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_products_search_trgm'), table_name='products', postgresql_ops={'search_text': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_products_tenant_cat_price'), table_name='products')
    op.drop_column('products', 'search_text')
    op.add_column('tenant_settings', sa.Column('delivery_info', sa.Text(), nullable=True))
    op.add_column('tenant_settings', sa.Column('delivery_fee_city', sa.Float(), nullable=True))
    op.add_column('tenant_settings', sa.Column('delivery_fee_regions', sa.Float(), nullable=True))
    op.add_column('tenant_settings', sa.Column('free_delivery_from', sa.Float(), nullable=True))
    op.add_column('tenant_settings', sa.Column('delivery_days_city', sa.String(length=64), nullable=True))
    op.add_column('tenant_settings', sa.Column('delivery_days_regions', sa.String(length=64), nullable=True))
    op.add_column('tenant_settings', sa.Column('payment_info', sa.Text(), nullable=True))
    op.add_column('tenant_settings', sa.Column('warranty_info', sa.Text(), nullable=True))
    op.add_column('tenant_settings', sa.Column('return_policy', sa.Text(), nullable=True))
    op.add_column('tenant_settings', sa.Column('working_hours', sa.String(length=255), nullable=True))
    op.add_column('tenant_settings', sa.Column('faq', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_settings', 'faq')
    op.drop_column('tenant_settings', 'working_hours')
    op.drop_column('tenant_settings', 'return_policy')
    op.drop_column('tenant_settings', 'warranty_info')
    op.drop_column('tenant_settings', 'payment_info')
    op.drop_column('tenant_settings', 'delivery_days_regions')
    op.drop_column('tenant_settings', 'delivery_days_city')
    op.drop_column('tenant_settings', 'free_delivery_from')
    op.drop_column('tenant_settings', 'delivery_fee_regions')
    op.drop_column('tenant_settings', 'delivery_fee_city')
    op.drop_column('tenant_settings', 'delivery_info')
    op.add_column('products', sa.Column('search_text', sa.TEXT(), sa.Computed("sotuvchi_norm((((((COALESCE(name, ''::character varying))::text || ' '::text) || (COALESCE(category, ''::character varying))::text) || ' '::text) || COALESCE(description, ''::text)))", persisted=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_products_tenant_cat_price'), 'products', ['tenant_id', 'category', 'price'], unique=False)
    op.create_index(op.f('ix_products_search_trgm'), 'products', ['search_text'], unique=False, postgresql_ops={'search_text': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_products_name_trgm'), 'products', [sa.literal_column('sotuvchi_norm(name::text)')], unique=False, postgresql_ops={'sotuvchi_norm(name::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###
