"""team groups and order confirmation

Revision ID: 6bab3b849b4e
Revises: 69c7a05e88be
Create Date: 2026-08-11 14:59:52.309318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bab3b849b4e'
down_revision: Union[str, Sequence[str], None] = '69c7a05e88be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('confirmed_by', sa.String(length=128), nullable=True))
    op.add_column('orders', sa.Column('receipt_message_id', sa.String(length=64), nullable=True))
    op.add_column('tenants', sa.Column('orders_group_id', sa.String(length=64), nullable=True))
    op.add_column('tenants', sa.Column('orders_group_title', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('work_group_id', sa.String(length=64), nullable=True))
    op.add_column('tenants', sa.Column('work_group_title', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('operators_group_id', sa.String(length=64), nullable=True))
    op.add_column('tenants', sa.Column('operators_group_title', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('group_pairing_code', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'group_pairing_code')
    op.drop_column('tenants', 'operators_group_title')
    op.drop_column('tenants', 'operators_group_id')
    op.drop_column('tenants', 'work_group_title')
    op.drop_column('tenants', 'work_group_id')
    op.drop_column('tenants', 'orders_group_title')
    op.drop_column('tenants', 'orders_group_id')
    op.drop_column('orders', 'receipt_message_id')
    op.drop_column('orders', 'confirmed_by')
    op.drop_column('orders', 'confirmed_at')
    op.drop_column('orders', 'longitude')
    op.drop_column('orders', 'latitude')
    # ### end Alembic commands ###
