"""conversation assignment and handoff reason

Revision ID: 6ca7c8866445
Revises: 79dad5992ffb
Create Date: 2026-08-08 17:39:31.446696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ca7c8866445'
down_revision: Union[str, Sequence[str], None] = '79dad5992ffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('assigned_user_name', sa.String(length=128), nullable=True))
    op.add_column('conversations', sa.Column('handoff_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'handoff_reason')
    op.drop_column('conversations', 'assigned_user_name')
    # ### end Alembic commands ###
