"""operator alerts: operator_chat_id, pairing, notify flags

Revision ID: 79dad5992ffb
Revises: 7e1f66ec0cbd
Create Date: 2026-08-08 17:35:37.626715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79dad5992ffb'
down_revision: Union[str, Sequence[str], None] = '7e1f66ec0cbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_settings', sa.Column('operator_chat_id', sa.String(length=64), nullable=True))
    op.add_column('tenant_settings', sa.Column('operator_name', sa.String(length=128), nullable=True))
    op.add_column('tenant_settings', sa.Column('pairing_code', sa.String(length=16), nullable=True))
    # server_default so existing rows get a value; NOT NULL would fail otherwise
    op.add_column('tenant_settings', sa.Column('notify_on_handoff', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('tenant_settings', sa.Column('notify_on_order', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_settings', 'notify_on_order')
    op.drop_column('tenant_settings', 'notify_on_handoff')
    op.drop_column('tenant_settings', 'pairing_code')
    op.drop_column('tenant_settings', 'operator_name')
    op.drop_column('tenant_settings', 'operator_chat_id')
    # ### end Alembic commands ###
