"""telegram business connection

Revision ID: b125213d6d04
Revises: f2fa0cf2322f
Create Date: 2026-09-22 14:49:05.323646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b125213d6d04'
down_revision: Union[str, Sequence[str], None] = 'f2fa0cf2322f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('telegram_business_connection_id', sa.String(length=128), nullable=True))
    op.add_column('tenants', sa.Column('telegram_business_connection_id', sa.String(length=128), nullable=True))
    op.add_column('tenants', sa.Column('telegram_business_owner_id', sa.String(length=64), nullable=True))
    op.add_column('tenants', sa.Column('telegram_business_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'telegram_business_enabled')
    op.drop_column('tenants', 'telegram_business_owner_id')
    op.drop_column('tenants', 'telegram_business_connection_id')
    op.drop_column('conversations', 'telegram_business_connection_id')
    # ### end Alembic commands ###
