"""guruhga reply orqali javob berish uchun ogohlantirish izlari

Revision ID: b931d7b23afb
Revises: fb948ae4927c
Create Date: 2026-09-28 15:07:32.381261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b931d7b23afb'
down_revision: Union[str, Sequence[str], None] = 'fb948ae4927c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default kerak: jadvalda allaqachon qatorlar bor, ularsiz
    # NOT NULL qo'shib bo'lmaydi.
    op.add_column(
        'conversations',
        sa.Column('handoff_alert_refs', postgresql.JSONB(astext_type=sa.Text()),
                  nullable=False, server_default=sa.text("'[]'::jsonb")),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'handoff_alert_refs')
    # ### end Alembic commands ###
