"""customer telegram handle

Revision ID: bfa94815ddb1
Revises: d4e27b2563cc
Create Date: 2026-08-11 16:42:10.919582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfa94815ddb1'
down_revision: Union[str, Sequence[str], None] = 'd4e27b2563cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('customer_username', sa.String(length=64), nullable=True))
    op.add_column('orders', sa.Column('customer_username', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'customer_username')
    op.drop_column('conversations', 'customer_username')
    # ### end Alembic commands ###
