"""notification routing: destinations and per-event routes

Every alert used to land wherever a hard-coded column pointed, so orders,
escalations and subscription warnings all arrived in the owner's one
personal chat. A destination is now a paired chat and the routing is data.
The backfill reproduces the old behaviour exactly.

Original: per-event routes

Revision ID: c792a894c872
Revises: 1b0c30b931f1
Create Date: 2026-08-13 15:20:21.955411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c792a894c872'
down_revision: Union[str, Sequence[str], None] = '1b0c30b931f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notify_channels',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('chat_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'chat_id', name='uq_notify_channel_tenant_chat')
    )
    op.create_index(op.f('ix_notify_channels_tenant_id'), 'notify_channels', ['tenant_id'], unique=False)
    op.add_column('orders', sa.Column('receipt_chat_id', sa.String(length=64), nullable=True))
    op.add_column('tenant_settings', sa.Column('notify_routes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ── Backfill ──────────────────────────────────────────────────────────────
    # Turn the four fixed columns into destinations, then write the routes that
    # reproduce today's behaviour exactly. Switching this feature on must change
    # nothing until an owner deliberately moves an alert somewhere else.
    op.execute(sa.text("""
        INSERT INTO notify_channels (id, tenant_id, chat_id, kind, title)
        SELECT 'nch-' || substr(md5(t.id || src.chat_id), 1, 12),
               t.id, src.chat_id, src.kind, coalesce(src.title, '')
        FROM tenants t
        JOIN LATERAL (
            SELECT s.operator_chat_id AS chat_id, 'private' AS kind,
                   coalesce(s.operator_name, 'Shaxsiy chat') AS title
            FROM tenant_settings s WHERE s.tenant_id = t.id AND s.operator_chat_id IS NOT NULL
            UNION ALL
            SELECT t.orders_group_id, 'group', coalesce(t.orders_group_title, 'Buyurtmalar guruhi')
            WHERE t.orders_group_id IS NOT NULL
            UNION ALL
            SELECT t.work_group_id, 'group', coalesce(t.work_group_title, 'Ishchi guruh')
            WHERE t.work_group_id IS NOT NULL
            UNION ALL
            SELECT t.operators_group_id, 'group', coalesce(t.operators_group_title, 'Operatorlar guruhi')
            WHERE t.operators_group_id IS NOT NULL
        ) src ON TRUE
        ON CONFLICT DO NOTHING
    """))

    # The routes below mirror the old hard-coded destinations one for one:
    #   order            -> operator chat
    #   handoff          -> operator chat AND operators group
    #   customer_waiting -> operator chat
    #   billing          -> operator chat, falling back to the orders group
    #   receipt          -> orders group
    #   delivery         -> work group, falling back to the orders group
    op.execute(sa.text("""
        UPDATE tenant_settings s SET notify_routes = routes.map
        FROM (
            SELECT t.id AS tenant_id,
                   jsonb_strip_nulls(jsonb_build_object(
                     'order',            CASE WHEN st.operator_chat_id IS NOT NULL
                                              THEN jsonb_build_array(st.operator_chat_id) END,
                     'handoff',          CASE WHEN st.operator_chat_id IS NOT NULL
                                                OR t.operators_group_id IS NOT NULL
                                              THEN (SELECT jsonb_agg(x) FROM unnest(
                                                     array_remove(ARRAY[st.operator_chat_id,
                                                                        t.operators_group_id], NULL)) x) END,
                     'customer_waiting', CASE WHEN st.operator_chat_id IS NOT NULL
                                              THEN jsonb_build_array(st.operator_chat_id) END,
                     'billing',          CASE WHEN coalesce(st.operator_chat_id, t.orders_group_id) IS NOT NULL
                                              THEN jsonb_build_array(coalesce(st.operator_chat_id, t.orders_group_id)) END,
                     'receipt',          CASE WHEN t.orders_group_id IS NOT NULL
                                              THEN jsonb_build_array(t.orders_group_id) END,
                     'delivery',         CASE WHEN coalesce(t.work_group_id, t.orders_group_id) IS NOT NULL
                                              THEN jsonb_build_array(coalesce(t.work_group_id, t.orders_group_id)) END
                   )) AS map
            FROM tenants t
            JOIN tenant_settings st ON st.tenant_id = t.id
        ) routes
        WHERE s.tenant_id = routes.tenant_id
          AND s.notify_routes IS NULL
          AND routes.map <> '{}'::jsonb
    """))

    # Receipts already posted went to the orders group; recording that keeps the
    # "payment confirmed" edit working on messages sent before this migration.
    op.execute(sa.text("""
        UPDATE orders o SET receipt_chat_id = t.orders_group_id
        FROM tenants t
        WHERE t.id = o.tenant_id
          AND o.receipt_message_id IS NOT NULL
          AND o.receipt_chat_id IS NULL
    """))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_settings', 'notify_routes')
    op.drop_column('orders', 'receipt_chat_id')
    op.drop_index(op.f('ix_notify_channels_tenant_id'), table_name='notify_channels')
    op.drop_table('notify_channels')
    # ### end Alembic commands ###
