"""payment slip photo

Revision ID: d4e27b2563cc
Revises: e67ec7cd6971
Create Date: 2026-08-11 15:50:39.738057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4e27b2563cc'
down_revision: Union[str, Sequence[str], None] = 'e67ec7cd6971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('last_photo_file_id', sa.String(length=256), nullable=True))
    op.add_column('orders', sa.Column('payment_photo_file_id', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_photo_file_id')
    op.drop_column('conversations', 'last_photo_file_id')
    # ### end Alembic commands ###
