"""conversation last location

Revision ID: e3c1ca71241e
Revises: 6bab3b849b4e
Create Date: 2026-08-11 15:03:47.100163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3c1ca71241e'
down_revision: Union[str, Sequence[str], None] = '6bab3b849b4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('last_latitude', sa.Float(), nullable=True))
    op.add_column('conversations', sa.Column('last_longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'last_longitude')
    op.drop_column('conversations', 'last_latitude')
    # ### end Alembic commands ###
