"""restore products search_text and trgm indexes

Revision ID: e67ec7cd6971
Revises: e3c1ca71241e
Create Date: 2026-08-11 15:09:57.695241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e67ec7cd6971'
down_revision: Union[str, Sequence[str], None] = 'e3c1ca71241e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Put back what an autogenerated migration silently dropped.

    Migration 69c7a05e88be was generated while search_text existed only in raw
    SQL, so Alembic saw it as stray and emitted DROPs — taking catalog search
    down with it. The column is now declared on the model, so this cannot
    recur. Written defensively so it is a no-op where nothing was lost.
    """
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("""
        CREATE OR REPLACE FUNCTION sotuvchi_norm(t text) RETURNS text
        LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE AS $fn$
            SELECT lower(translate(coalesce(t, ''), E'\u02bb\u02bc\u2018\u2019`\u00b4''"', ''))
        $fn$
    """)
    op.execute("""
        ALTER TABLE products
        ADD COLUMN IF NOT EXISTS search_text text
        GENERATED ALWAYS AS (
            sotuvchi_norm(coalesce(name,'') || ' ' || coalesce(category,'') || ' ' || coalesce(description,''))
        ) STORED
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_products_search_trgm ON products USING gin (search_text gin_trgm_ops)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_products_name_trgm ON products USING gin (sotuvchi_norm(name) gin_trgm_ops)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_products_tenant_cat_price ON products (tenant_id, category, price)")


def downgrade() -> None:
    """Intentionally empty: this migration only repairs, never removes."""
    pass
