"""google sheets catalog sync

Revision ID: efd918fb1e48
Revises: b125213d6d04
Create Date: 2026-09-23 14:31:26.044025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efd918fb1e48'
down_revision: Union[str, Sequence[str], None] = 'b125213d6d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_settings', sa.Column('google_sheet_url', sa.Text(), nullable=True))
    op.add_column('tenant_settings', sa.Column('google_sheet_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenant_settings', sa.Column('google_sheet_product_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_settings', 'google_sheet_product_count')
    op.drop_column('tenant_settings', 'google_sheet_synced_at')
    op.drop_column('tenant_settings', 'google_sheet_url')
    # ### end Alembic commands ###
