"""initial schema

Squashed from the 28 incremental migrations built up before launch — the
product was never deployed, so there is no production history to preserve,
and 28 files of "add column then fix a typo in it" is pure overhead. Every
raw-SQL object below (extensions, the `sotuvchi_norm()` function, the trigram
indexes) was read back off a database that had the full original chain
applied, not hand-copied from the old files — see alembic/env.py's
RAW_SQL_INDEXES for why autogenerate can't produce these on its own.

Revision ID: f2fa0cf2322f
Revises:
Create Date: 2026-09-07 12:07:57.035992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.db.models

# revision identifiers, used by Alembic.
revision: str = 'f2fa0cf2322f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The extension and the normalization function must exist before any
    # table that depends on them (products.search_text calls sotuvchi_norm()).
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("""
        CREATE OR REPLACE FUNCTION public.sotuvchi_norm(t text)
         RETURNS text
         LANGUAGE sql
         IMMUTABLE PARALLEL SAFE STRICT
        AS $function$
                    SELECT lower(translate(coalesce(t, ''), E'ʻʼ‘’`´''"', ''))
                $function$
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('fail_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_login_attempts_window_start'), 'login_attempts', ['window_start'], unique=False)
    op.create_table('plans',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('price_uzs', sa.Numeric(precision=18, scale=2, asdecimal=False), server_default='0', nullable=False),
    sa.Column('max_products', sa.Integer(), nullable=True),
    sa.Column('max_ai_messages_monthly', sa.Integer(), nullable=True),
    sa.Column('max_operators', sa.Integer(), nullable=True),
    sa.Column('duration_days', sa.Integer(), server_default='30', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('platform_admins',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_admins_email'), 'platform_admins', ['email'], unique=True)
    op.create_table('platform_ai_settings',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('style_text', sa.Text(), nullable=False),
    sa.Column('guardrails_text', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.String(length=64), nullable=True),
    sa.Column('admin_email', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_audit_log_action'), 'platform_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_platform_audit_log_created_at'), 'platform_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_platform_audit_log_tenant_id'), 'platform_audit_log', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('telegram_contact', sa.String(length=128), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_note', sa.Text(), nullable=True),
    sa.Column('balance', sa.Numeric(precision=18, scale=2, asdecimal=False), server_default='0', nullable=False),
    sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_trial', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('auto_renew', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('dunning_stage', sa.Integer(), nullable=True),
    sa.Column('telegram_bot_token', app.db.models.EncryptedStr(length=512), nullable=True),
    sa.Column('telegram_bot_username', sa.String(length=128), nullable=True),
    sa.Column('telegram_webhook_secret', app.db.models.EncryptedStr(length=512), nullable=True),
    sa.Column('orders_group_id', sa.String(length=64), nullable=True),
    sa.Column('orders_group_title', sa.String(length=255), nullable=True),
    sa.Column('work_group_id', sa.String(length=64), nullable=True),
    sa.Column('work_group_title', sa.String(length=255), nullable=True),
    sa.Column('operators_group_id', sa.String(length=64), nullable=True),
    sa.Column('operators_group_title', sa.String(length=255), nullable=True),
    sa.Column('group_pairing_code', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_tenant_id'), 'categories', ['tenant_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('telegram_username', sa.String(length=64), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('orders_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_spent', sa.Numeric(precision=18, scale=2, asdecimal=False), server_default='0', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.create_index('ix_customers_tenant_seen', 'customers', ['tenant_id', 'last_seen_at'], unique=False)
    op.create_index('uq_customer_tenant_phone', 'customers', ['tenant_id', 'phone'], unique=True, postgresql_where=sa.text('phone IS NOT NULL'))
    op.create_table('notify_channels',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('chat_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'chat_id', name='uq_notify_channel_tenant_chat')
    )
    op.create_index(op.f('ix_notify_channels_tenant_id'), 'notify_channels', ['tenant_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2, asdecimal=False), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('plan_name', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    op.create_table('platform_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('admin_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['platform_admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index(op.f('ix_platform_sessions_admin_id'), 'platform_sessions', ['admin_id'], unique=False)
    op.create_index(op.f('ix_platform_sessions_expires_at'), 'platform_sessions', ['expires_at'], unique=False)
    op.create_table('products',
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=2, asdecimal=False), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('search_text', sa.Text(), sa.Computed("sotuvchi_norm(coalesce(name,'') || ' ' || coalesce(category,'') || ' ' || coalesce(description,''))", persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'id')
    )
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    op.create_table('telegram_updates',
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('update_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='1', nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'update_id')
    )
    op.create_index(op.f('ix_telegram_updates_received_at'), 'telegram_updates', ['received_at'], unique=False)
    op.create_index(op.f('ix_telegram_updates_status'), 'telegram_updates', ['status'], unique=False)
    op.create_table('tenant_settings',
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('bot_enabled', sa.Boolean(), nullable=False),
    sa.Column('sheets_sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('ai_name', sa.String(length=64), nullable=False),
    sa.Column('ai_tone', sa.String(length=32), nullable=False),
    sa.Column('ai_language', sa.String(length=8), nullable=False),
    sa.Column('greeting_message', sa.Text(), nullable=True),
    sa.Column('auto_handoff_after', sa.Integer(), nullable=False),
    sa.Column('delivery_info', sa.Text(), nullable=True),
    sa.Column('delivery_fee_city', sa.Numeric(precision=18, scale=2, asdecimal=False), nullable=True),
    sa.Column('delivery_fee_regions', sa.Numeric(precision=18, scale=2, asdecimal=False), nullable=True),
    sa.Column('free_delivery_from', sa.Numeric(precision=18, scale=2, asdecimal=False), nullable=True),
    sa.Column('delivery_days_city', sa.String(length=64), nullable=True),
    sa.Column('delivery_days_regions', sa.String(length=64), nullable=True),
    sa.Column('payment_info', sa.Text(), nullable=True),
    sa.Column('warranty_info', sa.Text(), nullable=True),
    sa.Column('return_policy', sa.Text(), nullable=True),
    sa.Column('working_hours', sa.String(length=255), nullable=True),
    sa.Column('faq', sa.Text(), nullable=True),
    sa.Column('operator_chat_id', sa.String(length=64), nullable=True),
    sa.Column('operator_name', sa.String(length=128), nullable=True),
    sa.Column('pairing_code', sa.String(length=16), nullable=True),
    sa.Column('notify_routes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('customer_id', sa.String(length=64), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=64), nullable=True),
    sa.Column('last_latitude', sa.Float(), nullable=True),
    sa.Column('last_longitude', sa.Float(), nullable=True),
    sa.Column('last_photo_file_id', sa.String(length=256), nullable=True),
    sa.Column('customer_username', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('assigned_user_id', sa.String(length=64), nullable=True),
    sa.Column('assigned_user_name', sa.String(length=128), nullable=True),
    sa.Column('handoff_reason', sa.Text(), nullable=True),
    sa.Column('fail_streak', sa.Integer(), nullable=False),
    sa.Column('off_topic_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('abuse_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'channel', 'external_id', name='uq_conv_tenant_channel_ext')
    )
    op.create_index(op.f('ix_conversations_customer_id'), 'conversations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_conversations_external_id'), 'conversations', ['external_id'], unique=False)
    op.create_index(op.f('ix_conversations_tenant_id'), 'conversations', ['tenant_id'], unique=False)
    op.create_table('customer_identities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'channel', 'external_id', name='uq_identity_tenant_channel_ext')
    )
    op.create_index(op.f('ix_customer_identities_customer_id'), 'customer_identities', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_identities_tenant_id'), 'customer_identities', ['tenant_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_phone', sa.String(length=64), nullable=False),
    sa.Column('telegram_id', sa.String(length=64), nullable=True),
    sa.Column('conversation_id', sa.String(length=64), nullable=True),
    sa.Column('source_update_id', sa.BigInteger(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2, asdecimal=False), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('payment_photo_file_id', sa.String(length=256), nullable=True),
    sa.Column('customer_username', sa.String(length=64), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.String(length=128), nullable=True),
    sa.Column('receipt_message_id', sa.String(length=64), nullable=True),
    sa.Column('receipt_chat_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_conversation_id'), 'orders', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_tenant_id'), 'orders', ['tenant_id'], unique=False)
    op.create_index('uq_orders_tenant_source_update', 'orders', ['tenant_id', 'source_update_id'], unique=True, postgresql_where=sa.text('source_update_id IS NOT NULL'))
    op.create_table('user_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('sender', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=32), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index('ix_messages_tenant_created', 'messages', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2, asdecimal=False), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###

    # Expression/trigram indexes over sotuvchi_norm() and GIN trgm ops — the
    # model can't express these, so autogenerate would read them as stray and
    # DROP them on the next migration (see RAW_SQL_INDEXES in alembic/env.py).
    op.execute("CREATE INDEX ix_products_search_trgm ON products USING gin (search_text gin_trgm_ops)")
    op.execute("CREATE INDEX ix_products_name_trgm ON products USING gin (sotuvchi_norm(name) gin_trgm_ops)")
    op.create_index('ix_products_tenant_cat_price', 'products', ['tenant_id', 'category', 'price'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_products_tenant_cat_price', table_name='products')
    op.execute("DROP INDEX IF EXISTS ix_products_name_trgm")
    op.execute("DROP INDEX IF EXISTS ix_products_search_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.drop_index('ix_messages_tenant_created', table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('uq_orders_tenant_source_update', table_name='orders', postgresql_where=sa.text('source_update_id IS NOT NULL'))
    op.drop_index(op.f('ix_orders_tenant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_conversation_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_customer_identities_tenant_id'), table_name='customer_identities')
    op.drop_index(op.f('ix_customer_identities_customer_id'), table_name='customer_identities')
    op.drop_table('customer_identities')
    op.drop_index(op.f('ix_conversations_tenant_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_external_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_customer_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tenant_settings')
    op.drop_index(op.f('ix_telegram_updates_status'), table_name='telegram_updates')
    op.drop_index(op.f('ix_telegram_updates_received_at'), table_name='telegram_updates')
    op.drop_table('telegram_updates')
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_platform_sessions_expires_at'), table_name='platform_sessions')
    op.drop_index(op.f('ix_platform_sessions_admin_id'), table_name='platform_sessions')
    op.drop_table('platform_sessions')
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_notify_channels_tenant_id'), table_name='notify_channels')
    op.drop_table('notify_channels')
    op.drop_index('uq_customer_tenant_phone', table_name='customers', postgresql_where=sa.text('phone IS NOT NULL'))
    op.drop_index('ix_customers_tenant_seen', table_name='customers')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_categories_tenant_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_platform_audit_log_tenant_id'), table_name='platform_audit_log')
    op.drop_index(op.f('ix_platform_audit_log_created_at'), table_name='platform_audit_log')
    op.drop_index(op.f('ix_platform_audit_log_action'), table_name='platform_audit_log')
    op.drop_table('platform_audit_log')
    op.drop_table('platform_ai_settings')
    op.drop_index(op.f('ix_platform_admins_email'), table_name='platform_admins')
    op.drop_table('platform_admins')
    op.drop_table('plans')
    op.drop_index(op.f('ix_login_attempts_window_start'), table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###

    op.execute("DROP FUNCTION IF EXISTS public.sotuvchi_norm(text)")
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
