"""operator jim qolganda raqam yuborish uchun claim ustuni

Revision ID: fb948ae4927c
Revises: 504005907259
Create Date: 2026-09-27 09:13:19.540417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb948ae4927c'
down_revision: Union[str, Sequence[str], None] = '504005907259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('contact_reminded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'contact_reminded_at')
    # ### end Alembic commands ###
